name: Auto Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 'v14.15.5'

      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      - name: Lint
        run: yarn lint
      
      - name: Unit Test
        run: yarn test:unit
        
      - name: E2E Test
        run: yarn test:e2e
